# Generated by Django 3.0.2 on 2020-08-18 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='patient',
            fields=[
                ('cid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('mobile_no', models.IntegerField()),
                ('birthyear', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
    ]
