# Generated by Django 3.0.2 on 2020-08-18 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='birthyear',
        ),
    ]
