# Generated by Django 3.0.2 on 2020-08-18 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_remove_patient_birthyear'),
    ]

    operations = [
        migrations.CreateModel(
            name='record',
            fields=[
                ('rid', models.AutoField(primary_key=True, serialize=False)),
                ('total_ammount', models.IntegerField()),
                ('bill', models.FileField(blank=True, upload_to='bill/')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.patient')),
            ],
        ),
    ]
